version: "3.7"
services:
  
  mysql-db:
    # image: mysql:8.0
    build:
      context: ./sql
    restart: always
    container_name: mysql-db
    volumes:
      - my-db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_HOST=127.0.0.1
    ports:
      - '7010:3306'
    expose:
      - '7010'
    networks:
      - app-network

  app:
    build:
      args:
        user: www
        uid: 1000
      context: '.'
    container_name: laravel-app
    restart: unless-stopped
    # working_dir: /var/www/
    volumes:
      - ./:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  my-db: {}
